name: Build with Platformio

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ghcr.io/bertmelis/pio-test-container

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          pio run -e default -v
